### PR TITLE
chore(dep): removal of custom jansi version

### PR DESCRIPTION
**Pull request by goldmann**

### CODE REVIEW

**Comment by goldmann** [comment]
Related: #179.

@vibe13 Do you remember why we added custom Jansi version? I tested the CLI with this removal and it works fine.

**Comment by goldmann** [comment]
Ok, probably because of the `Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiOutputStream` error.

**Comment by goldmann** [comment]
Since we upgraded to Quarkus 3, we can now merge this.

**Comment by vibe13** [comment]
@goldmann I have missed the old message but yes, that is exactly why I had to use a custom jansi version, a class was relocated and I had issues with the build finder.

**Review by vibe13 — APPROVED** [review]
Ok so let's remove the custom version now! :-) Thanks!

**Pull request merged**
