### PR TITLE
[SBOMER-219] - Store trigger information

### PR DESCRIPTION
**Pull request by vibe13**

### CODE REVIEW

**Comment by vibe13** [comment]
@goldmann I need to:
* add SQL scrips (to update the model and migrate old UMBMessages to new RequestEvent)
* double check UI
* add DTOs? Do we want to expose request events?
* maybe more

**Review by goldmann — DISMISSED** [review]
OMG, this is huge, good job!

**Comment by goldmann** [comment]
Related to the question of exposing this data -- I would say it;s not necessary now. Let's store it first and we will think about the proper way to present it later.

**Comment by vibe13** [comment]
> Related to the question of exposing this data -- I would say it;s not necessary now. Let's store it first and we will think about the proper way to present it later.

Yep, let's first get them and then we can think what to do with such information later. Thanks!

**Review by goldmann — DISMISSED** [review]

**Comment by vibe13** [comment]
@goldmann I have updated the PR mainly to rebase on top of latest fixes on main, and I have implemented the check for existing messages in the DB with the new format. I have also refactored the RequestEventRepository so we don't have to duplicate the queries for H2 in AlternativeRequestEventRepository, now it's handled automatically.

**Review by goldmann — APPROVED** [review]

**Comment by goldmann** [comment]
Let's do it!

**Pull request merged**
