### PR TITLE
Add script to automate the setup of sdkman and java

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Comment by goldmann** [comment]
Thanks for this! I would leave the instructions in the doc in addition to the note about script. The reason is that someone could already have SDKMAN! installed and they would not expect to have someone mess with their config.

**Review by goldmann — CHANGES_REQUESTED** [review]
Thanks for this! I would leave the instructions in the doc in addition to the note about script. The reason is that someone could already have SDKMAN! installed and they would not expect to have someone mess with their config.

**Comment by dwalluck** [comment]
Good point. I've now left the old section entirely as it was and just split it into two sections (automatic and manual install).

**Comment by dwalluck** [comment]
I compared this script to the one for the CI, and I see that the CI has this additional step to install the internal certs.

I install haven't installed the internal certs into the new JDK yet locally as there is no mention in the dev docs. I wonder if we should add something here (maybe in a different PR).

**Review by goldmann — APPROVED** [review]

**Pull request merged**
