### PR TITLE
Convert paths to strings rather than hardcoding the path

### PR DESCRIPTION
**Pull request by dwalluck**
This fixes issues with paths and also avoid the `assertEquals` with lists.

### CODE REVIEW

**Comment by goldmann** [comment]
Similarly to my comment in https://github.com/project-ncl/sbomer/pull/632, I would leave expectations to be strings.

**Comment by goldmann** [comment]
I don't think it was broken before, was it? If not, I wouldn't touch it, because it decreases readability of the tests. Again, I prefer having plain strings in assertions. We do target POSIX-only.

**Comment by dwalluck** [comment]
Yes, technically the current code would only fail on Windows since while Java allows `/` to create paths just fine, when you print them they are going to print with `\`, e.g., `Path.of("foo/bar").toString() == "foo\bar"`;

**Comment by goldmann** [comment]
Windows is not our (dev or target) platform, I would better leave the code as it was (better readability).

**Comment by goldmann** [comment]
Closing this PR, see above comment.

**Pull request closed without merging**
