### PR TITLE
Set e2e packaging to pom

### PR DESCRIPTION
**Pull request by dwalluck**
This pom gives an error for me, and I must be using the same Maven version (since I tried with `mvnw`). But I wasn't sure what was intended here.

### CODE REVIEW

**Comment by dwalluck** [comment]
To be clear, without this PR, we are seeing this, right?

```
./mvnw clean install -DskipTests
```


```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.1.2:install (default-install) on project sbomer-e2e: The packaging plugin for project sbomer-e2e did not assign a file to the build artifact -> [Help 1]
```

**Comment by goldmann** [comment]
I don't know really. But now I found that this breaks vscode for e2e module.

**Comment by goldmann** [comment]
Oh, btw, I don't use the `install` phase in this project.

**Comment by goldmann** [comment]
I added a revert for this as part of https://github.com/project-ncl/sbomer/pull/649.

**Pull request merged**
